[parity]
chain = "spec.json"
base_path = "/home/ubuntu/openethaws/parity11"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8453
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x006a8e26c9653d22f1cadb22a81428deaa8554be"
reseal_on_txs = "none"
force_sealing = true