[parity]
chain = "spec.json"
base_path = "/home/ubuntu/openethaws/parity14"
[network]
port = 30306
[rpc]
port = 8546
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8456
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x002db24c08ed9397bc77a554e55f80d56be7b15f"
reseal_on_txs = "none"
force_sealing = true