[parity]
chain = "spec.json"
base_path = "/home/ubuntu/openethaws/parity10"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8452
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x0038658156bcb555c1aa24d1adabb57c36fbcd6d"
reseal_on_txs = "none"
force_sealing = true