[parity]
chain = "spec.json"
base_path = "/home/srisht/dirtyjunk/openethereum/parity4"
[network]
port = 30304
[rpc]
port = 8544
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8454
