[parity]
chain = "spec.json"
base_path = "/home/ubuntu/openethaws/parity15"
[network]
port = 30307
[rpc]
port = 8547
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8457
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x004f49d9267bce6bdefc0fe9065269fa5d24ead9"
reseal_on_txs = "none"
force_sealing = true