[parity]
chain = "spec.json"
base_path = "/home/srisht/dirtyjunk/openethereum/parity5"
[network]
port = 30305
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8455
