[parity]
chain = "spec.json"
base_path = "/home/srisht/dirtyjunk/openethereum/parity6"
[network]
port = 30306
[rpc]
port = 8546
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8456
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x006137d98307ab6691ccedb7a10b295da8ae1035"
reseal_on_txs = "none"
force_sealing = true