[parity]
chain = "spec.json"
base_path = "/home/ubuntu/openethaws/parity13"
[network]
port = 30305
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8455
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00734b960d1edd54e50192e47acfdc8af0fbbd20"
reseal_on_txs = "none"
force_sealing = true