[parity]
chain = "spec.json"
base_path = "/home/srisht/dirtyjunk/openethereum/parity7"
[network]
port = 30307
[rpc]
port = 8547
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8457
